### ISSUE TITLE
Missing: "flat format" for proto

### ISSUE THREAD

**Issue by TheAlexLichter** [theogravity/immutable-x-openapi#3]
Hey 👋 

I wanted to try the OpenAPI specs. Unfortunately, `https://api.godsunchained.com/v0/proto?format=flat` doesn't seem to be valid as the `format` query param is not known for the proto endpoint.

**Comment by theogravity** [comment]
This should be possible to fix as OpenAPI allows for alternative response definitions. I'll look into it tonight. Do you know if this only applies to the proto endpoint?

https://swagger.io/docs/specification/describing-responses/

See `Can I have different responses based on a request parameter?`

**Comment by TheAlexLichter** [comment]
I'm not sure whether this only applies to the `proto` endpoint or all but I think the proto is the most common (if not only) use case 😋

**Comment by theogravity** [comment]
I added the format query field to the proto list (I didn't see it work for proto by id) and the model for it, but OpenAPI 3.0 does not support dynamic object properties (3.1 should, but it's still too new that there is no tooling around it), so I couldn't set the flat proto model to the response for the proto list. I did add an empty object as an alternative, but not sure how certain client generators will treat that.

https://github.com/theogravity/immutable-x-openapi/commit/5430e92e115c671c2611945665127aefd2d15492
